activation: relu
base_data_path: /mnt/data/
base_dataset_name: cifar10
base_epochs: 50
base_lr: 0.1
batch_log: false
batch_size: 128
clip_update_threshold: 3.0
clip_updates: true
disable_wandb: false
loss_name: ce-loss
model_name: cifar-vgglike
momentum: 0.9
n_channels: 3
norm_backward: false
propagator_name: lfp-epsilon
reward_kwargs: {}
reward_name: softmaxlossreward
savepath: /mnt/output
scheduler_name: onecyclelr
seed: 7240
transfer_training: false
verbose: false
wandb_key: <wandb-key>
wandb_project_name: cifar-basemodels
weight_decay: 0.0
